spring:
  graphql:
    graphiql:
      enabled: true
    path: /graphql
  datasource:
    url: jdbc:postgresql://localhost:5432/example
    driver-class-name: org.postgresql.Driver
    username: judex
    password: 12345
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/db-changelog.xml
server:
  port: 8080
  address: 0.0.0.0