
spring:
  graphql:
    graphiql:
      enabled: true
    path: /graphql
  datasource:
    url: jdbc:postgresql://localhost:5432/example
    driver-class-name: org.postgresql.Driver
    username: judex
    password: 12345
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      host: localhost:27017
      database: maindb
    redis:
      password: 6k_j76,dDUl_
      host: localhost
      port: 6379
  cache:
    type: redis
    cache-names: redis-cache
    redis:
      time-to-live: 30000
  messages:
    basename: i18n/messages
  liquibase:
    change-log: classpath:db/db-changelog.xml
server:
  port: 8080
  address: 0.0.0.0
minio:
  url: http://localhost:9000
  port: 9000
  access-key: judex
  secret-key: password
  secure: false
  bucket: minio-storage
  image-size: 10485760
logging:
  level:
    "liquibase": info
springdoc:
  api-docs:
    path: /swagger-ui